language: python
python:
- '2.7'
- '3.3'
sudo: required
services:
  - docker
script:
  - echo hello world for now
deploy:
  provider: script
  script: make deploy
  skip_cleanup: true
  on:
      condition: $TRAVIS_BRANCH == "master" || -n $TRAVIS_TAG
