language: python
python:
- '2.7'
- '3.6'
sudo: required
services:
  - docker
env:
  - SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
  - SSL_CERT_DIR=/etc/ssl/certs
  - REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
script:
  - make test
  - make tag
deploy:
  provider: script
  script: make deploy
  skip_cleanup: true
  on:
    tags: true
